const path = require('node:path');
const IMAGE = new Set(['.png','.jpg','.jpeg','.webp','.avif','.bmp','.tiff']);
const VIDEO = new Set(['.mp4','.webm','.mov','.mkv','.m4v','.avi','.gif']);
function mediaType(file) { const ext=path.extname(file).toLowerCase(); if(IMAGE.has(ext))return 'image'; if(VIDEO.has(ext))return 'video'; throw new Error('Формат не поддерживается. Выберите фото или видео.'); }
function dimensions(width,height) { width=Number(width);height=Number(height); if(!Number.isInteger(width)||!Number.isInteger(height)||width<320||height<320||width>7680||height>7680||width*height>34000000)throw new Error('Разрешение: от 320 до 7680 px, до 34 Мп.'); return {width:width-width%2,height:height-height%2}; }
function filters({width,height,fit='contain',ultra=false}) { const d=dimensions(width,height); if(!['contain','cover','stretch'].includes(fit))throw new Error('Неизвестный режим кадрирования');const w=d.width,h=d.height; const scale=fit==='stretch'?`scale=${w}:${h}:flags=lanczos`:fit==='cover'?`scale=${w}:${h}:force_original_aspect_ratio=increase:flags=lanczos,crop=${w}:${h}`:`scale=${w}:${h}:force_original_aspect_ratio=decrease:flags=lanczos,pad=${w}:${h}:(ow-iw)/2:(oh-ih)/2:color=0x181221`;return [ultra?'hqdn3d=1.2:1.2:4:4':null,scale,ultra?'unsharp=5:5:0.65:5:5:0,eq=contrast=1.035:saturation=1.10:brightness=0.005':null,'setsar=1'].filter(Boolean).join(','); }
function publicAsset(item){return {...item,path:undefined,thumb:undefined,url:`velora://media/${item.id}`,thumbnail:`velora://thumb/${item.id}`};}
function validPinterest(url){const u=new URL(url);if(u.protocol!=='https:'||u.username||u.password||u.port)throw new Error('Нужна HTTPS-ссылка Pinterest.');const h=u.hostname.toLowerCase();if(!['pinterest.com','www.pinterest.com','ru.pinterest.com','uk.pinterest.com','pin.it'].includes(h)&&!h.endsWith('.pinimg.com'))throw new Error('Поддерживаются Pinterest и pinimg.com. Другой файл можно загрузить с компьютера.');return u;}
function errorText(e){return String(e?.message||e).replace(/AIza[\w-]+/g,'[ключ скрыт]').replace(/([?&]key=)[^&\s]+/gi,'$1[скрыто]').slice(0,800);}
module.exports={mediaType,dimensions,filters,publicAsset,validPinterest,errorText};
