const fs=require('node:fs/promises');
const path=require('node:path');
const {spawn}=require('node:child_process');
const sharp=require('sharp');
const {mediaType,filters,dimensions}=require('./core.cjs');
const binary=p=>p.replace('app.asar'+path.sep,'app.asar.unpacked'+path.sep);
const ffmpeg=binary(require('ffmpeg-static'));
const ffprobe=binary(require('ffprobe-static').path);
function run(exe,args,{signal,progress,duration}={}){return new Promise((resolve,reject)=>{let output='',errors='';const child=spawn(exe,args,{windowsHide:true,signal}); child.stdout.on('data',b=>{output+=b; if(output.length>2000000)output=output.slice(-1000000);if(progress&&duration){const a=String(b).match(/out_time_us=(\d+)/);if(a)progress(Math.min(98,Number(a[1])/1000000/duration*100));}});child.stderr.on('data',b=>{errors=(errors+b).slice(-6000);});child.once('error',reject);child.once('close',code=>code===0?resolve(output):reject(new Error(signal?.aborted?'Обработка отменена.':`Не удалось обработать файл. ${errors.slice(-600)}`)));});}
async function probe(file){const data=JSON.parse(await run(ffprobe,['-v','error','-show_streams','-show_format','-of','json',file]));const v=data.streams.find(x=>x.codec_type==='video');if(!v||!v.width||!v.height)throw new Error('В файле нет читаемого изображения или видео.');const rotation=v.side_data_list?.find(x=>x.rotation)?.rotation||Number(v.tags?.rotate)||0;return {width:Math.abs(rotation)%180===90?v.height:v.width,height:Math.abs(rotation)%180===90?v.width:v.height,duration:Number(data.format.duration)||0,codec:v.codec_name};}
async function metadata(file){if(mediaType(file)==='image'){const m=await sharp(file,{limitInputPixels:100000000}).metadata();const rotated=[5,6,7,8].includes(m.orientation);return {width:rotated?m.height:m.width,height:rotated?m.width:m.height,duration:0};}return probe(file);}
async function thumbnail(file,out,type){if(type==='image')await sharp(file).rotate().resize(640,400,{fit:'cover'}).jpeg({quality:85}).toFile(out);else await run(ffmpeg,['-hide_banner','-loglevel','error','-y','-i',file,'-frames:v','1','-vf','scale=640:400:force_original_aspect_ratio=increase,crop=640:400',out]);}
async function transcode(file,out,options,job){const d=dimensions(options.width,options.height);const type=mediaType(file);if(type==='image'){let pipeline=sharp(file).rotate();if(options.ultra)pipeline=pipeline.median(3);pipeline=pipeline.resize(d.width,d.height,{fit:options.fit==='stretch'?'fill':options.fit==='cover'?'cover':'contain',background:'#181221',kernel:'lanczos3'});if(options.ultra)pipeline=pipeline.sharpen({sigma:0.8}).modulate({saturation:1.1,brightness:1.005});await pipeline.png().toFile(out);return;}const args=['-hide_banner','-y','-i',file,'-map','0:v:0','-map','0:a?','-vf',filters(options),'-c:v','libx264','-preset','fast','-crf',options.ultra?'16':'19','-pix_fmt','yuv420p','-threads','4','-c:a','aac','-b:a','192k','-movflags','+faststart','-progress','pipe:1','-nostats',out];await run(ffmpeg,args,job);}
async function aiFrame(file,out,job){await run(ffmpeg,['-hide_banner','-loglevel','error','-y','-i',file,'-frames:v','1','-vf','scale=1920:1920:force_original_aspect_ratio=decrease',out],job);}
async function videoBackground(file,background,out,options,job){const {width:w,height:h}=dimensions(options.width,options.height);let fx=`[0:v]scale=${w}:${h}[bg];[1:v]scale=${w}:${h}:force_original_aspect_ratio=decrease:flags=lanczos[fg];[bg][fg]overlay=(W-w)/2:(H-h)/2:shortest=1,setsar=1`;if(options.ultra)fx+=',unsharp=5:5:0.6:5:5:0,eq=contrast=1.035:saturation=1.10';await run(ffmpeg,['-hide_banner','-y','-loop','1','-i',background,'-i',file,'-filter_complex',fx,'-map','1:a?','-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-threads','4','-c:a','aac','-shortest','-movflags','+faststart','-progress','pipe:1','-nostats',out],job);}
module.exports={run,ffmpeg,ffprobe,metadata,thumbnail,transcode,aiFrame,videoBackground,probe};
