const fs=require('node:fs/promises');
const {createWriteStream}=require('node:fs');
const {Readable,Transform}=require('node:stream');
const {pipeline}=require('node:stream/promises');
const dns=require('node:dns/promises');
const {validPinterest}=require('./core.cjs');
async function request(url,signal){for(let n=0;n<8;n++){const u=validPinterest(url);const ips=await dns.lookup(u.hostname,{all:true});if(!ips.length||ips.some(({address:a})=>/^(127\.|10\.|192\.168\.|169\.254\.|172\.(1[6-9]|2\d|3[01])\.|0\.|::|f[cd]|fe80)/i.test(a)))throw new Error('Локальные сетевые адреса запрещены.');const r=await fetch(u,{redirect:'manual',signal,headers:{'User-Agent':'Mozilla/5.0 (compatible; Velora/0.1)'}});if(r.status>=300&&r.status<400){await r.body?.cancel();url=new URL(r.headers.get('location'),u).href;continue;}if(!r.ok)throw new Error('Pinterest не отдал файл. Сохраните его вручную и загрузите с компьютера.');return r;}throw new Error('Слишком много перенаправлений Pinterest.');}
const decode=s=>s.replace(/&amp;/g,'&').replace(/&#x2F;/gi,'/').replace(/&#39;/g,"'").replace(/&quot;/g,'"');
async function importPinterest(url,base,signal){let r=await request(url,signal);if(r.headers.get('content-type')?.includes('text/html')){const reader=r.body.getReader();let html='',size=0;while(true){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>5000000){await reader.cancel();throw new Error('Страница слишком большая. Загрузите файл вручную.');}html+=new TextDecoder().decode(value);}const meta=[...html.matchAll(/<meta\b[^>]*>/gi)].map(m=>Object.fromEntries([...m[0].matchAll(/([\w:-]+)\s*=\s*["']([^"']*)["']/g)].map(a=>[a[1].toLowerCase(),decode(a[2])])));const media=meta.find(m=>['og:video','og:video:secure_url'].includes(m.property))||meta.find(m=>m.property==='og:image');if(!media?.content)throw new Error('Этот пин недоступен без входа или не содержит прямого файла. Сохраните оригинал и загрузите его сюда.');r=await request(media.content,signal);}
const mime=r.headers.get('content-type')?.split(';')[0];const ext={'image/jpeg':'.jpg','image/png':'.png','image/webp':'.webp','image/gif':'.gif','video/mp4':'.mp4','video/webm':'.webm'}[mime];if(!ext)throw new Error('Ссылка не содержит поддерживаемого фото или видео.');const out=base+ext;let bytes=0;try{await pipeline(Readable.fromWeb(r.body),new Transform({transform(chunk,e,cb){bytes+=chunk.length;cb(bytes>2*1024**3?new Error('Файл по ссылке превышает 2 ГБ. Загрузите его с компьютера.'):null,chunk);}}),createWriteStream(out),{signal});return out;}catch(e){await fs.rm(out,{force:true});throw e;}}
module.exports={importPinterest};
