const {BrowserWindow,screen,powerMonitor}=require('electron');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const {execFile}=require('node:child_process');
const {promisify}=require('node:util');
const exec=promisify(execFile);
let winapi;
function windows(){if(winapi)return winapi;const k=require('koffi'),u=k.load('user32.dll');const rect=k.struct('VELORA_RECT',{left:'long',top:'long',right:'long',bottom:'long'});const point=k.struct('VELORA_POINT',{x:'long',y:'long'});const enumProc=k.proto('bool __stdcall VeloraEnumProc(void *hwnd, intptr_t data)');winapi={k,find:u.func('void * __stdcall FindWindowW(str16, str16)'),findEx:u.func('void * __stdcall FindWindowExW(void *, void *, str16, str16)'),enum:u.func('bool __stdcall EnumWindows(VeloraEnumProc *, intptr_t)'),enumProc,send:u.func('intptr_t __stdcall SendMessageTimeoutW(void *, uint32, uintptr_t, intptr_t, uint32, uint32, _Out_ uintptr_t *)'),parent:u.func('void * __stdcall SetParent(void *, void *)'),getParent:u.func('void * __stdcall GetParent(void *)'),style:u.func('intptr_t __stdcall GetWindowLongPtrW(void *, int)'),setStyle:u.func('intptr_t __stdcall SetWindowLongPtrW(void *, int, intptr_t)'),pos:u.func('bool __stdcall SetWindowPos(void *, void *, int, int, int, int, uint32)'),client:u.func('bool __stdcall ScreenToClient(void *, _Inout_ VELORA_POINT *)'),rect:u.func('bool __stdcall GetWindowRect(void *, _Out_ VELORA_RECT *)'),foreground:u.func('void * __stdcall GetForegroundWindow()'),className:u.func('int __stdcall GetClassNameW(void *, _Out_ char16_t *, int)'),spi:u.func('bool __stdcall SystemParametersInfoW(uint32, uint32, str16, uint32)')};return winapi;}
function attach(win,display){const a=windows(),h=win.getNativeWindowHandle().readBigUInt64LE();const prog=a.find('Progman',null);if(!prog)throw new Error('Рабочий стол Explorer не найден. Перезапустите Проводник и повторите.');a.send(prog,0x052c,0,0,0,1500,[0]);let worker=null;const cb=a.k.register(hwnd=>{const icons=a.findEx(hwnd,null,'SHELLDLL_DefView',null);if(icons)worker=a.findEx(null,hwnd,'WorkerW',null);return true;},a.k.pointer(a.enumProc));try{a.enum(cb,0);}finally{a.k.unregister(cb);}if(!worker)worker=a.findEx(prog,null,'WorkerW',null);if(!worker)throw new Error('Windows не предоставила слой живых обоев. Статичные обои доступны.');const style=Number(a.style(h,-16));a.setStyle(h,-16,(style&~0x80000000)|0x40000000);a.parent(h,worker);if(!a.getParent(h))throw new Error('Не удалось прикрепить видео к рабочему столу.');const b=screen.dipToScreenRect(null,display.bounds),p={x:b.x,y:b.y};a.client(worker,p);if(!a.pos(h,null,p.x,p.y,b.width,b.height,0x0040|0x0010|0x0004))throw new Error('Не удалось разместить обои.');return {attached:!!a.getParent(h),width:b.width,height:b.height};}
async function staticWallpaper(file){if(process.platform==='win32'){if(!windows().spi(20,0,file,3))throw new Error('Windows отклонила смену обоев.');return 'Обои установлены для рабочего стола Windows.';}const desktop=(process.env.XDG_CURRENT_DESKTOP||'').toLowerCase();const uri=pathToFileURL(file).href;if(desktop.includes('gnome')||desktop.includes('ubuntu')){await exec('gsettings',['set','org.gnome.desktop.background','picture-uri',uri]);try{await exec('gsettings',['set','org.gnome.desktop.background','picture-uri-dark',uri]);}catch{}return 'Обои установлены в GNOME.';}if(desktop.includes('cinnamon')){await exec('gsettings',['set','org.cinnamon.desktop.background','picture-uri',uri]);return 'Обои установлены в Cinnamon.';}if(desktop.includes('kde')){const script=`var ds = desktops(); for (var i=0; i<ds.length; i++) { var d=ds[i]; d.wallpaperPlugin='org.kde.image'; d.currentConfigGroup=['Wallpaper','org.kde.image','General']; d.writeConfig('Image',${JSON.stringify(uri)}); }`;let last;for(const bin of ['qdbus6','qdbus','qdbus-qt5']){try{await exec(bin,['org.kde.plasmashell','/PlasmaShell','org.kde.PlasmaShell.evaluateScript',script]);return 'Обои установлены в KDE Plasma.';}catch(e){last=e;}}throw new Error('Для KDE требуется qdbus6 или qdbus.');}if(process.env.XDG_SESSION_TYPE!=='wayland'){await exec('feh',['--bg-fill',file]);return 'Обои установлены через feh.';}throw new Error('Статичные обои: поддерживаются GNOME, KDE и Cinnamon. В этой среде экспортируйте картинку и установите её через настройки рабочего стола.');}
class Wallpaper{
  constructor(onState){this.windows=[];this.active=null;this.paused=false;this.onState=onState;this.locked=false;this.settings={pauseBattery:true,pauseFullscreen:true};powerMonitor.on('lock-screen',()=>{this.locked=true;this.refresh();});powerMonitor.on('unlock-screen',()=>{this.locked=false;this.refresh();});powerMonitor.on('on-battery',()=>this.refresh());powerMonitor.on('on-ac',()=>this.refresh());this.timer=setInterval(()=>this.refresh(),3000);this.timer.unref();}
  capabilities(){return {live:process.platform==='win32'||(process.platform==='linux'&&process.env.XDG_SESSION_TYPE!=='wayland'),platform:process.platform,session:process.env.XDG_SESSION_TYPE||'',desktop:process.env.XDG_CURRENT_DESKTOP||'',note:process.platform==='linux'&&process.env.XDG_SESSION_TYPE==='wayland'?'Wayland: статичные обои доступны; для видео войдите в сеанс X11.':'Видео работает, пока Velora запущена в трее.'};}
  async apply(item,displayId,fit){if(item.type==='image'){const result=await staticWallpaper(item.path);this.stop();this.active={id:item.id,type:'image'};this.onState();return result;}if(!this.capabilities().live)throw new Error(this.capabilities().note);const displays=displayId==='all'?screen.getAllDisplays():screen.getAllDisplays().filter(d=>String(d.id)===String(displayId));if(!displays.length)throw new Error('Экран отключён. Выберите другой экран.');const pending=[];try{for(const d of displays){const w=new BrowserWindow({x:d.bounds.x,y:d.bounds.y,width:d.bounds.width,height:d.bounds.height,show:false,frame:false,transparent:false,backgroundColor:'#000000',skipTaskbar:true,focusable:false,hasShadow:false,roundedCorners:false,type:process.platform==='linux'?'desktop':undefined,webPreferences:{contextIsolation:true,sandbox:true,nodeIntegration:false,backgroundThrottling:false}});pending.push(w);w.setIgnoreMouseEvents(true);w.webContents.setWindowOpenHandler(()=>({action:'deny'}));w.webContents.on('will-navigate',e=>e.preventDefault());await w.loadFile(path.join(__dirname,'player.html'),{query:{src:`velora://media/${item.id}`,fit}});await w.webContents.executeJavaScript('window.ready');w.showInactive();if(process.platform==='win32')attach(w,d);}this.stop();this.windows=pending;this.active={id:item.id,type:'video',displayId,fit};this.refresh();this.onState();return 'Живые обои включены. Velora продолжит работать в трее.';}catch(e){pending.forEach(w=>w.destroy());throw e;}}
  refresh(){let fullscreen=false;if(this.active?.type==='video'&&process.platform==='win32'&&this.settings.pauseFullscreen){try{const a=windows(),h=a.foreground(),r={};const name=Buffer.alloc(512);a.className(h,name,256);const cls=name.toString('utf16le').replace(/\0.*$/s,'');if(!['Progman','WorkerW','Shell_TrayWnd'].includes(cls)&&a.rect(h,r)){fullscreen=screen.getAllDisplays().some(d=>{const b=screen.dipToScreenRect(null,d.bounds);return r.left<=b.x&&r.top<=b.y&&r.right>=b.x+b.width&&r.bottom>=b.y+b.height;});}}catch{}}const pause=this.paused||this.locked||fullscreen||(this.settings.pauseBattery&&powerMonitor.isOnBatteryPower());if(this.lastPause===pause)return;this.lastPause=pause;for(const w of this.windows)if(!w.isDestroyed())w.webContents.executeJavaScript(pause?'document.querySelector("video").pause()':'document.querySelector("video").play().catch(()=>{})').catch(()=>{});this.onState();}
  stop(){for(const w of this.windows)if(!w.isDestroyed())w.destroy();this.windows=[];this.active=null;this.lastPause=undefined;this.onState();}
}
module.exports={Wallpaper,attach,staticWallpaper};
